FROM n8nio/n8n:1.106.3

# Copiamos el script y dejamos permisos
COPY startup.sh /usr/local/bin/startup.sh
USER root
RUN chmod +x /usr/local/bin/startup.sh
USER node

# Entramos por nuestro script, que a su vez llama al entrypoint oficial
ENTRYPOINT ["/usr/local/bin/startup.sh"]

EXPOSE 8080
